### ISSUE TITLE
What does the Figure2 mean？

### ISSUE THREAD

**Issue by Ethanwl** [siyuhuang/crowdcount-stackpool#2]
I have read your papers. But I don't understand what the Figure2 tries to explain and what the colors(gray, blue, and orange) represent. Can you give me some ideas about that? Thank you!

**Comment by siyuhuang** [comment]
@Ethanwl 

1. The colored regions in Fig. 2 denote the activated regions on feature maps (eg., values>0 after ReLU). The white regions are not activated. 

2. Fig. 2 shows a very simple example to discuss how a larger receptive field leads to a stronger scale invariance. There is a scale variation between two input feature maps. The feature map after 2×2 max-pooling changes, while the feature map after 4×4 max-pooling stays the same.
