### ISSUE TITLE
Questions about patches

### ISSUE THREAD

**Issue by Ethanwl** [siyuhuang/crowdcount-stackpool#5]
1. Your paper says that we randomly crop 9 patches on each training image, where all the patches are half the size of the original image. Actually after running `create_training_set_shtech.m`, the patches' height and width are about a quarter of the original images.
2. https://github.com/siyuhuang/crowdcount-stackpool/blob/403be5a9945abd52fe2e4f1857edb99704ce1d0e/data_preparation/create_training_set_shtech.m#L49-L61
What does the code try to do? The condition `w <= 2*wn2`  is equivalent to `w<=16*floor(w/64)`. But only when `w=0 or w<=-16`, the condition meets.

**Comment by siyuhuang** [comment]
@Ethanwl 

1. The patch size is a quarter of original image. Thanks for pointing out, we will revised our paper.

2. `create_training_set_shtech.m` is a copy of [https://github.com/svishwa/crowdcount-mcnn/blob/master/data_preparation/create_training_set_shtech.m](https://github.com/svishwa/crowdcount-mcnn/blob/master/data_preparation/create_training_set_shtech.m). The referenced code is maybe used for some extreme cases.
