### ISSUE TITLE
about the  kernel

### ISSUE THREAD

**Issue by Yellow-Champagne** [siyuhuang/crowdcount-stackpool#7]
Hello, is the transformation density map using a geometric adaptive kernel?

**Comment by siyuhuang** [comment]
We do not use geometric adaptive kernel. Sigma is fixed as [here](https://github.com/siyuhuang/crowdcount-stackpool/blob/838d635b180a0fea143aa4937800b9740bc70715/data_preparation/get_density_map_gaussian.m#L19).
