### ISSUE TITLE
When I run test.py, I find that there is no save_model folder, and I cannot find the .h5 file

### ISSUE THREAD

**Issue by wlc-git** [siyuhuang/crowdcount-stackpool#8]

**Comment by siyuhuang** [comment]
You should first train the model using `train.py` to get the model weights saved as `.h5 `

It is easy to train the models, so we do not provide the pretrained models.

**Comment by wlc-git** [comment]
Thank you for your answers, I will train immediately




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuhuang/crowdcount-stackpool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月10日(星期五) 上午8:56
收件人:&nbsp;"siyuhuang/crowdcount-stackpool"<crowdcount-stackpool@noreply.github.com&gt;;
抄送:&nbsp;" "<1129480429@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [siyuhuang/crowdcount-stackpool] When I run test.py, I find that there is no save_model folder, and I cannot find the .h5 file (#8)





 
You should first train the model using train.py to get the model weights saved as .h5 .
 
It is easy to train the models, so we do not provide the pretrained model.
